### ISSUE TITLE
Cannot run UI

### ISSUE THREAD

**Issue by sguiheux** [ovh-ux/ovh-icon-database-front#45]
### Description
Missing information in readme to run the UI

### Steps to Reproduce

1. [First Step]
`npm install`
2. [Second Step]
`npm run dev`

**Actual behavior:**

```
Env var OSS_URL is missing !
Env var OSS_AUTH is missing !
Env var OSS_CONTAINER is missing !
Env var API_URL is missing !
 95% emitting                                                                           

 DONE  Compiled successfully in 4521ms                                                                                                                                                                                         10:03:39

 I  Your application is running here: http://localhost:8080                                                                                                                                                               TypeError: Cannot read property 'split' of null
    at required (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/requires-port/index.js:13:23)
    at Object.common.setupOutgoing (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/http-proxy/lib/http-proxy/common.js:102:7)
    at Array.stream (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:120:14)
    at ProxyServer.<anonymous> (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/http-proxy/lib/http-proxy/index.js:80:21)
    at middleware (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/http-proxy-middleware/lib/index.js:41:19)
    at app.use (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-server/lib/Server.js:256:22)
    at Layer.handle [as handle_request] (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/express/lib/router/index.js:317:13)
    at /home/sguiheux/Dev/ovh-icon-database-front/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/express/lib/router/index.js:335:12)
    at next (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/express/lib/router/index.js:275:10)
    at goNext (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/middleware.js:27:49)
    at processRequest (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/middleware.js:66:21)
    at Object.ready (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/lib/Shared.js:166:29)
    at Object.handleRequest (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/lib/Shared.js:209:10)
    at /home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/middleware.js:44:11
es/webpack-dev-middleware/lib/Shared.js:166:29)
    at Object.handleRequest (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/lib/Shared.js:209:10)
    at /home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/middleware.js:44:11
ome/sguiheux/Dev/ovh-icon-database-front/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/express/lib/router/index.js:335:12)
    at next (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/express/lib/router/index.js:275:10)
    at goNext (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/middleware.js:27:49)
    at processRequest (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/middleware.js:66:21)
    at Object.ready (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/lib/Shared.js:166:29)
    at Object.handleRequest (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/lib/Shared.js:209:10)
    at /home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/middleware.js:44:11
es/webpack-dev-middleware/lib/Shared.js:166:29)
    at Object.handleRequest (/home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/lib/Shared.js:209:10)
    at /home/sguiheux/Dev/ovh-icon-database-front/node_modules/webpack-dev-middleware/middleware.js:44:11
```

**Comment by Memoyr** [comment]
+1

**Comment by antleblanc** [comment]
ping @kimung (maybe he could help you!)

**Comment by antleblanc** [comment]
@sguiheux I'm sorry to inform you that this project is sadly not maintained anymore.

I bet that @kimung is the Man that can probably give you more information around
this project but as you notice, he didn't has the time to look back at it.

So I close this issue.
